# Set the initial path
# ccach ってどうなんだろうね。ちょっと外しておく
# 
# Gcc-6.2 用
# path=( /bin /usr/bin /usr/local/bin $HOME/.local/bin(N-/) /sbin /usr/sbin/ \
# 	/usr/local/sbin /usr/local/go/bin $HOME/.gem/ruby/2.3.0/bin $HOME/.local/go/bin )
#
# Gcc-7-20170511 用
path=(/opt/gcc-7-20170511/bin  /bin /usr/bin /usr/local/bin $HOME/.local/bin(N-/) /sbin /usr/sbin/ \
     /usr/local/sbin /usr/local/go/bin $HOME/.gem/ruby/2.3.0/bin $HOME/.local/go/bin )

export LANG=ja_JP.UTF-8

# Set some defaults for graphical systems
export XDG_DATA_DIRS=/usr/share/
export XDG_CONFIG_DIRS=/etc/xdg/

# for xorg installation
export XORG_PREFIX="/usr"
export XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=/etc \
    --localstatedir=/var --disable-static"

# for xorg config
export VDPAU_DRIVER=va_gl

# for Qt5
QT5DIR=/opt/qt5
#export PATH=$PATH:$QT5DIR/bin
path=($path $QT5DIR/bin)
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$QT5DIR/lib/pkgconfig
export QT5DIR

# ユーザーで make して sudo make install するときに同じフラグを使う
# -s を付けていたけど、firefox で nm シンボルが無いと言われた。物によっては -s がビルド中
# に必要みたいだから削除。
#
# 挑戦的な CFLAGS
export CFLAGS="-march=native -O3 -ffast-math"
#
# わりと安全な CFLAGS
# export CFLAGS="-march=native -O2"
#
# 保守的な CFLAGS
# export CFLAGS="-O2"
#
export CXXFLAGS=$CFLAGS
export KCFLAGS=$CFLAGS

# PGI compiler
export PGI=/opt/pgi
export MANPATH=/usr/share/man:/usr/man:/usr/local/share/man:/usr/local/man:\
/opt/pgi/linux86-64/17.4/man
path=($path	/opt/pgi/linux86-64/17.4/bin)
